{
  "comments": [
    {
      "unresolved": false,
      "key": {
        "uuid": "3ad09cc9_9c9b03fb",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5756
      },
      "writtenOn": "2022-04-29T20:28:47Z",
      "side": 1,
      "message": "Investigating",
      "revId": "88702f178c7a1be5757d9095fe00955dd6303985",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    },
    {
      "unresolved": false,
      "key": {
        "uuid": "32bee2a2_9ce251ca",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 1
      },
      "lineNbr": 0,
      "author": {
        "id": 5756
      },
      "writtenOn": "2022-05-04T22:16:01Z",
      "side": 1,
      "message": "recheck\n\nupdated the pypi ovs 2.17.1 build to 2.17.1.post1 to fix a bug.",
      "revId": "88702f178c7a1be5757d9095fe00955dd6303985",
      "serverId": "4a232e18-c5a9-48ee-94c0-e04e7cca6543"
    }
  ]
}